// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareRide.API.Models
{
    public partial class Feedbacks
    {
        public int FeedbackId { get; set; }
        public int RideId { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public int IstUser { get; set; }
        public DateTime IstDate { get; set; }
        public string IstIp { get; set; }

        public virtual Users FromUser { get; set; }
        public virtual Rides Ride { get; set; }
        public virtual Users ToUser { get; set; }
    }
}