// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ShareRide.API.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ShareRide.API.Models
{
    public partial interface IShareRideContextProcedures
    {
        Task<List<SP_GetUsersResult>> SP_GetUsersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
