// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareRide.API.Models
{
    public partial class Rides
    {
        public Rides()
        {
            Feedbacks = new HashSet<Feedbacks>();
            RideRequests = new HashSet<RideRequests>();
            RideStops = new HashSet<RideStops>();
        }

        public int RideId { get; set; }
        public int UserId { get; set; }
        public int VehicleId { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string TotalSeats { get; set; }
        public DateTime StartTime { get; set; }
        public int LstUser { get; set; }
        public DateTime LstDate { get; set; }
        public string LstIp { get; set; }

        public virtual Users User { get; set; }
        public virtual Vehicles Vehicle { get; set; }
        public virtual ICollection<Feedbacks> Feedbacks { get; set; }
        public virtual ICollection<RideRequests> RideRequests { get; set; }
        public virtual ICollection<RideStops> RideStops { get; set; }
    }
}