// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ShareRide.API.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ShareRide.API.Models
{
    public partial class ShareRideContext
    {
        private IShareRideContextProcedures _procedures;

        public virtual IShareRideContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ShareRideContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IShareRideContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SP_GetUsersResult>().HasNoKey().ToView(null);
        }
    }

    public partial class ShareRideContextProcedures : IShareRideContextProcedures
    {
        private readonly ShareRideContext _context;

        public ShareRideContextProcedures(ShareRideContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_GetUsersResult>> SP_GetUsersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_GetUsersResult>("EXEC @returnValue = [dbo].[SP_GetUsers]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
