// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareRide.API.Models
{
    public partial class Vehicles
    {
        public Vehicles()
        {
            Rides = new HashSet<Rides>();
        }

        public int VehicleId { get; set; }
        public int UserId { get; set; }
        public string VehicleType { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleDetails { get; set; }
        public string VehicleImageUrl { get; set; }
        public string VehicleNumber { get; set; }
        public int LstUser { get; set; }
        public DateTime LstDate { get; set; }
        public string LstIp { get; set; }

        public virtual Users User { get; set; }
        public virtual ICollection<Rides> Rides { get; set; }
    }
}